version: "3.3"
services:

  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    networks:
      - "backend"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jiraalerts
    volumes:
      - "db-data:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    networks:
      - "backend"
    links:
      - "mysql:db"

networks:
  backend:

volumes:
  db-data:
