CREATE TABLE JIRA_CONNECTION_DATA(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  URL VARCHAR(255) NOT NULL,
  MODIFIED_AT DATETIME NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO JIRA_CONNECTION_DATA (ID, URL, MODIFIED_AT) VALUES (1, 'insert url here', CURRENT_TIMESTAMP());