version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      working_directory: ~/JiraAlerts
          environment:
            JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew check
workflows:
  version: 2
  test_jiraalerts:
    jobs:
      - test