version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
        name: test
        command: ./gradlew check

  sonarqube:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
        name: analyze
        command: if ["$CIRCLE_PR_NUMBER" = "" ]; then ./gradlew sonarqube -Dsonar.organization=$SONAR_ORG -Dsonar.projectName=$SONAR_PROJECT_NAME -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=SONAR_PROJECT_KEY -Dsonar.login=$SONAR_LOGIN

workflows:
  version: 2
  test_sonarqube:
    jobs:
      - test
      - sonarqube