CREATE TABLE DEVICE (
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
URL VARCHAR(255) NOT NULL,
TYPE INTEGER NOT NULL,
OWNER BIGINT NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT DEVICE_USER_FK	FOREIGN KEY (OWNER) REFERENCES USERS (ID)
);
