CREATE TABLE ROUTINE_QUERY (
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
JQL VARCHAR(255) NOT NULL,
MINUTES_FOR_RECOGNITION INTEGER NOT NULL,
ROUTINE_QUERY_STATE INTEGER NOT NULL,
OWNER BIGINT NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT ROUTINE_QUERY_USER_FK	FOREIGN KEY (OWNER) REFERENCES USERS (ID)
);
